name:               ais
version:            0.1.0.0
synopsis:           ygpark blog project from stack
description:        Please see README.md
homepage:           https://github.com/ygpark2/ygpark2.github.io#readme
license:            BSD3
license-file:       LICENSE
author:             Young Gyu Park
maintainer:         ygpark2@gmail.com
copyright:          2016 Young Gyu Park.
category:           Web
# build-type:         Simple
# cabal-version:      >= 1.10

Flag development
  Description: Development mode
  Default: False

Executable
  post
    main:
      Post.hs
    source-dirs:
      src
    dependencies:
      base >= 4.12.0.0 && < 5,
      cmdargs >= 0.10.14 && < 0.11,
      template >= 0.2.0.10 && < 0.3,
      filepath >= 1.4 && < 1.5,
      directory >= 1.3.3.0 && < 1.4,
      time >= 1.8.0.2 && < 1.9
    default-language: Haskell2010
    if flag(development)
      cpp-options: -DDEVELOPMENT
      ghc-options: -threaded -Wall -fwarn-tabs -funbox-strict-fields -O2
                   -fno-warn-unused-do-bind
    else
      ghc-options: -threaded -Wall -fwarn-tabs -funbox-strict-fields -O2
                   -fno-warn-unused-do-bind

  site
    main:
      Main.hs
    source-dirs:
      src
    dependencies:
      base >= 4.12.0.0 && < 5,
      hakyll >= 4.13.0.1 && < 5,
      hakyll-sass >= 0.2.4 && < 1,
      filepath >= 1.4 && < 1.5,
      process >= 1.6.5.0 && < 1.7,
      unordered-containers >= 0.2 && < 0.3,
      configurator >= 0.3 && < 0.5,
      text >= 1.2 && < 1.3,
      regex-compat >= 0.95 && < 0.97,
      containers >= 0.6.0.1 && < 0.7,
      pandoc >= 2.7.3 && < 3
    default-language: Haskell2010
    if flag(development)
      cpp-options: -DDEVELOPMENT
      ghc-options: -threaded -Wall -fwarn-tabs -funbox-strict-fields -O2
                   -fno-warn-unused-do-bind
    else
      ghc-options: -threaded -Wall -fwarn-tabs -funbox-strict-fields -O2
                   -fno-warn-unused-do-bind
